import Layout from "@/components/layout/Layout"


export const metadata = {
  title: 'CUET E-Bazar',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Layout>
        {children}
      </Layout>
    </>
  )
}
