import DashboardLayout from "@/components/layout/DashboardLayout"

export const metadata = {
  title: 'CUET E-Bazar',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <DashboardLayout>
        {children}
      </DashboardLayout>
    </>
  )
}
